import google.generativeai as genai
import os
from Image_to_text import extractText

genai.configure(api_key="")

model = genai.GenerativeModel('gemini-1.5-flash')

def init_gemini(content):
    if(content.startswith("https://")):
        textExt = extractText(content)
    else:
        textExt = content
    response = model.generate_content(f"{textExt} \n \n first understand yurself then give explanation and then give the answer ")
    return response.text
    # print("\n Answers Generated by the model : " , response.text)
